server:
  port: 8085

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: healthcenter
          uri: http://localhost:8085
          predicates:
            - Path=/reserves/**, 
        - id: isolationcamp
          uri: http://localhost:8086
          predicates:
            - Path=/isolationCamps/**, 
        - id: deliverycenter
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, 
        - id: citizeninfo
          uri: http://localhost:8082
          predicates:
            - Path=, 
        - id: testingcenter
          uri: http://localhost:8086
          predicates:
            - Path=/tests/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: healthcenter
          uri: http://healthcenter:8080
          predicates:
            - Path=/reserves/**, 
        - id: isolationcamp
          uri: http://isolationcamp:8080
          predicates:
            - Path=/isolationCamps/**, 
        - id: deliverycenter
          uri: http://deliverycenter:8080
          predicates:
            - Path=/deliveries/**, 
        - id: citizeninfo
          uri: http://citizeninfo:8080
          predicates:
            - Path=, 
        - id: testingcenter
          uri: http://testingcenter:8080
          predicates:
            - Path=/tests/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
